version: 2

sources:
  - name: intermediate
    database: health_demo
    tables:
      - name: int_clinical_trials
      - name: int_drugs
      - name: int_patients
      - name: int_physicians
      - name: int_trial_drug_assignments
      - name: int_trial_enrollments
      - name: int_adverse_events

models:
  # ----------------------------------------------------------------------------------------
  - name: dim_clinical_trials
    description: "Clinical Trials Dimension (Incremental - Merge)"
    columns:
      - name: dim_clinical_trial_id
        description: "Primary Key (clinical_id)"
        tests:
          - unique
          - not_null
      - name: trial_name
      - name: therapeutic_area
      - name: status
      - name: sponsor_name
      - name: phase
      - name: end_date
      - name: updated_at
  # ----------------------------------------------------------------------------------------
  - name: dim_drugs
    description: "Drugs Dimensions (Incremental - Merge)"
    columns:
      - name: dim_drug_id
        description: "Primary Key (drug_id)"
        tests:
          - unique
          - not_null
      - name: drug_name
      - name: generic_name
      - name: drug_class
      - name: manufacturer
      - name: approval_status
      - name: updated_at
  # ----------------------------------------------------------------------------------------
  - name: dim_patients
    description: "Patients Dimension (Incremental - Merge)"
    columns:
      - name: dim_patient_id
        description: "Primary Key (patient_id)"
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: date_of_birth
      - name: gender
        data_tests:
          - accepted_values:
              arguments:
                values: ["Male", "Female", "Other"]
      - name: address_state
      - name: insurance_provider
      - name: insurance_plan_code
      - name: dim_physician_id
        data_tests:
          - relationships:
              arguments:
                field: dim_physician_id
                to: ref('dim_physicians')
      - name: enrollment_status
      - name: created_at
      - name: updated_at
  # ----------------------------------------------------------------------------------------
  - name: dim_physicians
    description: "Physicians Dimension (Incremental - Merge)"
    columns:
      - name: dim_physician_id
        description: "Primary Key (physician_id)"
        tests:
          - unique
          - not_null
      - name: honorific
      - name: first_name
      - name: last_name
      - name: specialty
      - name: npi_number
      - name: employment_type
      - name: affiliated_hospital
      - name: license_state
      - name: updated_at
  # ----------------------------------------------------------------------------------------
  - name: fct_drug_assignments
    description: "Drug Assignments Fact (SCD2 - Maintain)"
    columns:
      - name: fct_drug_assignment_id
        description: "surrogate key (sha2 of (assignment_id | dim_clinical_trial_id | dim_drug_id))"
        tests:
          - unique
          - not_null
      - name: assignment_id
        tests:
          - not_null
      - name: dim_clinical_trial_id
        data_tests:
          - relationships:
              arguments:
                field: dim_clinical_trial_id
                to: ref('dim_clinical_trials')
      - name: dim_drug_id
        data_tests:
          - relationships:
              arguments:
                field: dim_drug_id
                to: ref('dim_drugs')
      - name: arm_label
      - name: frequency
      - name: dosage_mg
      - name: from_dt
      - name: to_dt
      - name: current_record
        data_tests:
          - accepted_values:
              arguments:
                values: ["0","1"]
  # ----------------------------------------------------------------------------------------
  - name: fct_trial_enrollments
    description: "Trial Enrollments Fact (SCD2 - Maintain)"
    columns:
      - name: fct_trial_enrollment_id
        description: "Surrogate key (sha2 of (enrollment_id + dim_clinical_trial_id + dim_patient_id))"
      - name: enrollment_id
      - name: dim_patient_id
        data_tests:
          - relationships:
              arguments:
                field: dim_patient_id
                to: ref('dim_patients')
      - name: dim_clinical_trial_id
        data_tests:
          - relationships:
              arguments:
                field: dim_clinical_trial_id
                to: ref('dim_clinical_trials')
      - name: enrolled_date
      - name: current_status
      - name: withdrawal_reason
      - name: withdrawal_date
      - name: updated_at
      - name: from_dt
      - name: to_dt
      - name: current_record
        data_tests:
          - accepted_values:
              arguments:
                values: ["0","1"]
  # ----------------------------------------------------------------------------------------
  - name: fct_adverse_events
    description: "Adverse Events Fact (SCD2 - Maintain)"
    columns:
      - name: fct_adverse_event_id
        description: "Surrogate key (sha2 of (fct_enrollment_id | dim_patient_id)))"
        tests:
          - unique
          - not_null
      - name: event_id
        tests:
          - unique
          - not_null
      - name: fct_trial_enrollment_id
        data_tests:
          - relationships:
              arguments:
                field: fct_trial_enrollment_id
                to: ref('fct_trial_enrollments')
      - name: dim_patient_id
        data_tests:
          - relationships:
              arguments:
                field: dim_patient_id
                to: ref('dim_patients')
      - name: reported_by
      - name: event_descriptions
      - name: event_date
      - name: severity
      - name: resolved_date
      - name: from_dt
      - name: to_dt
      - name: current_record
        data_tests:
          - accepted_values:
              arguments:
                values: ["0","1"]