version: 2


# LND TABLES ARE INTENTIONALLY BARE ON TESTING...
# THE PURPOSE OF THIS SCHEMA IS SIMPLY ACTING AS AN INGESTING POINT
# Traditionally:
#    Data would be ingested through pipeline
#    or Seed data would be supplementary
# in this demo, the files are loaded through seed just to maintain simplicity
# of the project and avoid additional pipelines

models:
  - name: raw_adverse_events
    columns:
      - name: enrollment_id
      - name: event_date
      - name: event_description
      - name: event_id
      - name: patient_id
      - name: reported_by
      - name: resolved_date
      - name: severity
  
  - name: raw_clinical_trials
    columns:
      - name: end_date
      - name: phase
      - name: sponsor_name
      - name: status
      - name: therapeutic_area
      - name: trial_id
      - name: trial_name
      - name: updated_at
  
  - name: raw_drugs
    columns:
      - name: drug_id
      - name: approval_status
      - name: drug_class
      - name: drug_name
      - name: generic_name
      - name: manufacturer
      - name: updated_at
  
  - name: raw_patients
    columns:
      - name: address_state
      - name: created_at
      - name: date_of_birth
      - name: enrollment_status
      - name: first_name
      - name: gender
      - name: insurance_plan_code
      - name: insurance_provider
      - name: last_name
      - name: patient_id
      - name: primary_physician_id
      - name: updated_at
  
  - name: raw_physicians
    columns:
      - name: affiliated_hospital
      - name: employment_type
      - name: full_name
      - name: license_state
      - name: npi_number
      - name: physician_id
      - name: specialty
      - name: updated_at
  
  - name: raw_trial_drug_assignments
    columns:
      - name: arm_label
      - name: assignment_id
      - name: dosage_mg
      - name: drug_id
      - name: frequency
      - name: trial_id
  
  - name: raw_trial_enrollments
    columns:
      - name: current_status
      - name: enrolled_date
      - name: enrollment_id
      - name: patient_id
      - name: trial_id
      - name: updated_at
      - name: withdrawal_date
      - name: withdrawal_reason